FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
   gcc \
   && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src
COPY .env /app/.env

EXPOSE 8502

CMD ["streamlit", "run", "src/streamlit_app.py", "--server.port=8502", "--server.address=0.0.0.0"]