services:
  tf-serving:
    image: tensorflow/serving:latest
    container_name: tf-serving
    environment:
      - MODEL_NAME=mnist
    volumes:
      - ./models/mnist:/models/mnist
      - ./monitoring/tf_serving_monitoring.config:/etc/tensorflow_serving/monitoring_config
    command:
      - --monitoring_config_file=/etc/tensorflow_serving/monitoring_config
      - --rest_api_port=8501

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./monitoring/nginx.conf:/etc/nginx/nginx.conf
      - ./monitoring/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - tf-serving

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - tf-serving
