services:
  tf-serving:
    image: tensorflow/serving:latest
    container_name: tf-serving
    environment:
      - MODEL_NAME=mnist
    volumes:
      - ./models/mnist:/models/mnist
      - ./monitoring/tf_serving_monitoring.config:/etc/tensorflow_serving/monitoring_config
    command:
      - --monitoring_config_file=/etc/tensorflow_serving/monitoring_config
      - --rest_api_port=8501
      - --model_config_file=/models/mnist/models.config
    ports:
      - "8501:8501"
    networks:
      - ml-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - tf-serving
    networks:
      - ml-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-app
    ports:
      - "8502:8502"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - MODEL_BASE_PATH=/app/models
      - TF_SERVING_URL=http://tf-serving:8501/v1/models/mnist
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - tf-serving
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
